services:

  # crdb:
  #   image: cockroachdb/cockroach:v19.2.2
  #   ports:
  #     - "26257:26257"
  #     - "8080:8080"
  #   command: start-single-node --insecure
  #   volumes:
  #     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

  postgredb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgre
      POSTGRES_DB: feed_database
      POSTGRES_PASSWORD: Isdof903wu489y7dfn1qi134bikbui34
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./database.postgre.sql:/docker-entrypoint-initdb.d/database.postgre.sql
    ports:
      - "5433:5432"